<a href="https://colab.research.google.com/github/Sarthak2608/Machine-Learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
print(np.absolute(-3))

3


In [0]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(5,)


In [0]:
b=np.array([[1,2,3],[4,5,6]])
print(np.shape)

<function shape at 0x7f3329092268>


In [0]:
bTranspose=b.T
print(bTranspose)

[[1 4]
 [2 5]
 [3 6]]


In [0]:
c=np.dot(b,bTranspose)
print(c)

[[14 32]
 [32 77]]


In [0]:
np.random.randint?

In [0]:
a=np.random.randint(10,1000,10)
print(a)

[879 342 426 990 394 126 177 190 655 253]


In [0]:
b=np.random.randint(10,100,(5,5))
print(b)


[[35 31 14 29 80]
 [87 38 15 66 22]
 [87 42 23 98 68]
 [78 87 26 88 97]
 [63 34 17 36 28]]


In [0]:
print(np.max(b),np.argmax(b))  #argmax return the index of maximum element

98 13


In [0]:
#unique number in array
a=[1,1,2,-3,4,4]
key,value=np.unique(a,return_counts=True);
print(key)
print(value)

[-3  1  2  4]
[1 2 1 2]


In [0]:
#Slicing of an array
mat=np.random.randint(10,100,(5,5))
print(mat)
slc=mat[1:5:2,1:5:2]  #It is zero based indexing and slc=mat[start:end:increment]
print(slc)


[[22 37 88 41 13]
 [90 88 46 37 33]
 [74 40 88 38 38]
 [82 91 44 16 78]
 [21 53 42 39 51]]
[[88 37]
 [91 16]]
